# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12RqpdMebvUqfbmUtJ1rU8KTqmJnmSTSv
"""

#! pip install streamlit

import streamlit as st
#import pandas as pd
# Title of the app
st.title('my first App')

#ask for name and display it
name = st.text_input("What's your name?")
st.write(f"Hello, {name}! Nice to meet you!")